[mypy]
python_version = 3.14
files = app
exclude = ^(\.venv|data|tests|scripts)/
python_executable = /Users/bytedance/Desktop/files/self/lania-zip/rag/.venv/bin/python
check_untyped_defs = True
warn_unused_ignores = True
show_error_codes = True
pretty = True

[mypy-chromadb.*]
ignore_missing_imports = True

[mypy-datasets.*]
ignore_missing_imports = True

[mypy-fastapi.*]
ignore_missing_imports = True

[mypy-httpx.*]
ignore_missing_imports = True

[mypy-langchain_openai.*]
ignore_missing_imports = True

[mypy-llama_index.*]
ignore_missing_imports = True

[mypy-pydantic.*]
ignore_missing_imports = True

[mypy-pydantic_settings.*]
ignore_missing_imports = True

[mypy-ragas.*]
ignore_missing_imports = True
